// Auto-generated English descriptions mapped by English item name
const D: Record<string, string> = {
  // Soups
  "Lentil Soup": "Traditional Iraqi lentil soup served with toasted bread and lemon",
  "Chicken Soup": "Rich chicken soup with fresh vegetables and herbs",
  "Vegetable Soup": "Seasonal vegetables slow-cooked with aromatic herbs",
  "Noor Land Special Soup": "Chef's special soup with Noor Land's secret blend",
  "Mushroom Soup": "Creamy mushroom soup with garlic and parsley",
  // Salads
  "Chicken Caesar Salad": "Crispy lettuce with golden croutons & parmesan cheese, served with Caesar dressing",
  "Green Salad": "Fresh tomatoes, cucumber, bell pepper, oregano and fresh mint leaves, served with lemon oil dressing",
  "Greek Salad": "Crispy lettuce, colored bell pepper, feta cheese, radish and black olives served with lemon emulsion",
  "Oriental Salad": "Fresh chopped vegetables in oriental style with pomegranate molasses",
  "Fattoush": "Mixed greens and veggies topped with crispy bread chunks, seasoned with olive oil, lemon juice and pomegranate molasses",
  "Rocca Salad": "Fresh rocket and thyme topped with onions, served with sumac",
  "Tabbouleh": "Chopped parsley with tomatoes, mint, onions and bulgur, seasoned with olive oil and lemon juice",
  // Cold Mezza
  "Labneh": "Creamy labneh with extra virgin olive oil and mint leaves",
  "Hummus Beiruti": "Chickpeas with parsley, onion and tomato, topped with olive oil",
  "Hummus": "Mashed chickpeas dip topped with virgin olive oil",
  "Beetroot Mutabal": "Hummus with our special beetroot mix",
  "Baba Ganoush": "Roasted eggplant mashed with tahini and lemon",
  "Betenjaniya": "Eggplant prepared in our special style with herbs",
  "Jajik": "Yogurt with cucumber and dried mint",
  "Vine Leaves": "Stuffed with parsley, tomato and onions",
  "Eggplant Moutabal": "Topped with fried eggplant, walnuts and pomegranate",
  "Quinoa Salad": "Quinoa with tomatoes, cucumber, bell pepper and mint leaves with lemon oil dressing",
  // Hot Mezza
  "Hummus with Meat": "Creamy hummus topped with sautéed meat, ghee and pine nuts",
  "Shrimp Provencal": "Sautéed in lemon butter with garlic and coriander",
  "Chicken Liver": "Sautéed in lemon or pomegranate sauce",
  "Fried Kibbeh": "Golden fried kibbeh stuffed with meat and onions",
  "Potato Harrah": "Potato cubes with spicy coriander seasoning",
  "Mix Sambousek": "Mix of fried cheese rolls, meat sambousek and fried kibbeh",
  "Grilled Halloumi": "Grilled halloumi cheese served with vegetables",
  "Cheese Rakakat": "Fried or grilled golden crispy cheese rolls",
  "Fried Potato with Cheese": "French fries topped with melted cheese",
  "Fatte Hummus": "Chickpea fatteh with yogurt, ghee and toasted nuts",
  "Eggplant Fatte": "Fried eggplant fatteh with yogurt and tahini",
  // Pasta
  "Spaghetti Bolognese": "Spaghetti with tomato sauce & minced meat, served with parmesan cheese",
  "Fettuccine Alfredo": "Fettuccine with grilled chicken, mushrooms, creamy sauce & fresh basil",
  "Penne Arrabiata": "Penne with spicy tomato sauce and herbs",
  "Lasagna": "Lasagna with bechamel sauce, tomato sauce, and topped with mozzarella cheese",
  "Carbonara": "Penne or fettuccini with turkey, cream sauce, eggs and parmesan cheese",
  // Oriental
  "Ouzi Lamb": "Two types of rice, served with oriental sauces",
  "Chicken Kabsa": "Yellow rice, grilled chicken, served with special kabsa sauce",
  "Maklouba Laham": "Special maklouba rice, vegetables, lamb meat served with yogurt",
  "Maklouba Chicken": "Special maklouba rice, vegetables, chicken served with yogurt",
  "Kubba with Yogurt & Rice": "Kubba cooked in yogurt served with white rice",
  "Quzi Sham with Lamb": "Premium Damascene quzi with lamb and toasted nuts",
  // International
  "Beef Steak Tenderloin": "Tenderloin beef, served with your choice of potato and sauce",
  "T-Bone Steak": "Steak with vegetable sauté served with potato and mushroom sauce",
  "Chicken Steak": "Chicken breast, vegetable sauté and potato, served with mushroom sauce",
  "Chicken Curry": "Served with rice and Iraqi bread",
  "Chicken Escalope": "Fried chicken breast, served with fries and garlic sauce",
  "Cordon Bleu Beef": "Beef stuffed with cheese served with special sauce",
  "Cordon Bleu Chicken": "Chicken stuffed with cheese served with vegetables",
  // Seafood
  "Seafood Platter": "Premium seafood platter with vegetable sauté and lemon butter sauce",
  "Hamour Harra": "Filet hamour served with dill sauce, vegetables and spinach",
  "Jumbo Shrimp": "Served with grilled vegetables and buffalo sauce",
  "Grilled Salmon": "Grilled salmon, vegetable sauté and mashed potato, served with lemon butter sauce",
  "Fish & Chips": "Fried fish fillet, served with fries and tartar sauce",
  // Sandwiches
  "Beef Burger": "Meat, lettuce, tomato, onion, pickles, served with fries",
  "Beef Cheese Burger": "Meat, lettuce, tomato, caramelized onion, pickles, cheese, served with fries",
  "Mushroom Cheese Burger": "Meat, sautéed mushroom, onion, and pickles, served with fries",
  "Chicken Burger": "Grilled chicken breast, grilled tomato, lettuce and pickles, served with fries",
  "Chicken Cheese Burger": "Grilled chicken breast, grilled tomato, cheese, lettuce and pickles, served with fries",
  "Chicken Fajita": "Marinated chicken breast, onion, pepper, mushroom served with sour cream, avocado sauce and hot sauce",
  "Club Sandwich": "Grilled chicken breast, turkey ham, fried eggs, tomato, lettuce, and cheese, served with fries",
  "French Fries with Cheese": "French fries topped with cheddar cheese",
  "Beef Shawarma": "Fresh beef shawarma with pickles and special sauce",
  "Chicken Shawarma": "Chicken shawarma with garlic sauce and pickles",
  // BBQ
  "Arabic Mixed Grill": "Kabab laham, tekka laham, tawook, served with French fries and garlic sauce",
  "Kabab Laham": "Fresh lamb kabab grilled over charcoal",
  "Chicken Kabab": "Marinated chicken kabab grilled over charcoal",
  "Laham Tikka": "Lamb tikka grilled over charcoal",
  "Chicken Tikka": "Marinated chicken tikka grilled over charcoal",
  "Arayes Meat": "Grilled meat arayes served with fries",
  "Boneless Chicken": "Marinated grilled chicken, served with fries and garlic sauce",
  "Grilled Lamb Chops": "Lamb chops, grilled tomato and onion, served with fries or white rice",
  "Kabab Eggplant": "Meat kabab with grilled eggplant",
  "Special Noor Land Kabab": "Pistachio kabab, eggplant kabab, vegetable kabab and Turkish kabab",
  // Pizza
  "Pepperoni": "Homemade dough, tomato sauce, topped with pepperoni and mozzarella cheese",
  "Four Seasons": "Four flavors: meat, chicken, vegetable and cheese",
  "Vegetarian": "Homemade dough, tomato sauce, fresh vegetables, onion, topped with black olives and mozzarella",
  "Margherita": "Homemade dough, tomato sauce, topped with mozzarella cheese",
  "Mexican": "Homemade dough, tomato sauce, grilled chicken, fresh vegetables, onion and mozzarella",
  "Seafood Pizza": "Homemade dough, bechamel sauce, pesto, topped with mozzarella cheese and seafood",
  "Cheese Kaake": "Baked stuffed cheese kaake",
  // Desserts
  "Tiramisu": "Mascarpone layers with espresso and cocoa",
  "Muhalabia": "Milk pudding with rose water and nuts",
  "Crème Caramel": "Smooth crème caramel with golden caramel layer",
  "Om Ali": "Hot om ali with nuts and cream",
  "Strawberry Cheese Cake": "Creamy cheesecake with fresh strawberry sauce",
  "Ice Cream (3 Scoops)": "Three scoops of your favorite flavors",
  "Fruit Salad": "Fresh seasonal fruits",
  "Sliced Fruit Platter": "Carefully sliced fresh seasonal fruits platter",
  // Hot Drinks
  "Cappuccino": "Espresso with steamed milk and smooth foam",
  "Cafe Latte": "Espresso with silky steamed milk",
  "Americano": "Long espresso with rich flavor",
  "Caffe Mocha": "Espresso with chocolate and steamed milk",
  "Hot Chocolate": "Rich hot chocolate with milk",
  "Espresso": "Concentrated espresso shot",
  "Turkish Coffee": "Traditional Turkish coffee",
  "Spanish Latte": "Latte with sweetened condensed milk",
  "Latte Macchiato": "Steamed milk with a touch of espresso",
  "Caramel Latte": "Latte with caramel sauce",
  "Caramel Cappuccino": "Cappuccino with caramel flavor",
  "Vanilla Cappuccino": "Cappuccino with vanilla flavor",
  // Tea
  "Iraqi Tea": "Traditional Iraqi tea",
  "Green Tea": "Refreshing green tea",
  "English Breakfast Tea": "Classic black tea",
  "Chamomile Tea": "Soothing chamomile tea",
  "Green Tea with Mint": "Green tea with fresh mint leaves",
  "Milk Tea (Karak)": "Karak milk tea with cardamom",
  "Hibiscus Tea": "Refreshing hibiscus tea",
  // Iced Coffee
  "Iced Noor Land": "Lotus, caramel sauce and milk — our signature drink",
  "Iced Caffe Latte": "Espresso with cold milk and ice",
  "Iced Cappuccino": "Iced cappuccino with cold foam",
  "Iced Spanish Latte": "Iced Spanish latte with condensed milk",
  "Iced Caffe Mocha": "Iced mocha with chocolate",
  "Iced Caramel": "Iced coffee with caramel sauce",
  "Iced Latte Macchiato": "Iced macchiato with distinctive layers",
  // Juices
  "Orange Juice": "Fresh squeezed orange juice daily",
  "Watermelon Juice": "Fresh refreshing watermelon",
  "Lemon Mint Juice": "Fresh lemon with mint leaves",
  "Grapefruit Juice": "Fresh grapefruit juice",
  "Apple Juice": "Freshly squeezed apple juice",
  "Carrot Juice": "Fresh carrot juice rich in vitamins",
  "Pineapple Juice": "Fresh tropical pineapple",
  "Strawberry Juice": "Fresh strawberry juice",
  "Peach Juice": "Fresh peach juice",
  "Kiwi Juice": "Fresh refreshing kiwi juice",
  "Maldives Cocktail": "Fresh orange, Maldives syrup and Perrier",
  // Mojitos
  "Pinacolada Mojito": "Pineapple and coconut with fresh mint",
  "Classic Mojito": "Mint and lemon with refreshing soda",
  "Apple Mojito": "Green apple with mint and lemon",
  "Pomegranate Mojito": "Fresh pomegranate with mint",
  // Smoothies
  "Banana Milk Smoothie": "Fresh banana with milk",
  "Banana Chocolate Smoothie": "Banana with rich chocolate",
  "Avocado Honey Smoothie": "Creamy avocado with natural honey",
  // Milkshakes
  "Noor Land Milkshake": "Noor Land special milkshake with mixed flavors",
  "Strawberry Milkshake": "Fresh strawberry with ice cream",
  "Oreo Milkshake": "Oreo cookies with vanilla ice cream",
  "Banana Milkshake": "Fresh banana with ice cream",
  "Lotus Milkshake": "Lotus biscuit with ice cream and caramel",
  // Fruit Salads
  "Grantilla Fruit Salad": "Fresh fruits with granola layers",
  "Kit Kat Salad": "Fruits with Kit Kat and chocolate",
  "Granch Salad": "Special granch fruit mix",
  "Tropical Salad": "Fresh tropical fruits",
  "Fruit Salad with Cream": "Seasonal fruits with fresh cream",
  "Emperor": "Premium layered fruits with nuts and honey",
  "Fruit Emperor": "Fruit emperor with banana and milk",
  "Special Emperor": "Emperor with special flavors",
  "Strawberry & Milk Emperor": "Emperor with strawberry and milk",
  // Cocktails
  "Noor Land Cocktail": "Noor Land special cocktail with distinctive fruit mix",
  "Fruit Cocktail": "Fresh mixed fruit cocktail",
  "Banana & Milk Cocktail": "Fresh banana with milk",
  "Chocolate & Milk Cocktail": "Milk with rich chocolate",
  "Orange, Banana & Apple Cocktail": "Refreshing fruit mix",
  "Pineapple & Kiwi Cocktail": "Fresh pineapple and kiwi",
  "Mango & Strawberry Cocktail": "Fresh mango and strawberry",
  // Crepes
  "Noor Land Crêpe": "Chef's special crêpe with chocolate, nuts and fruits",
  "Nutella Crêpe": "Crêpe filled with Nutella cream",
  "Lotus Crêpe": "Crêpe with lotus cream and crushed biscuit",
  "Oreo Crêpe": "Crêpe with Oreo pieces and white chocolate cream",
  "Kinder Crêpe": "Crêpe with Kinder chocolate",
  "Fruit Crêpe": "Crêpe with fresh fruit assortment",
  "Nuts Crêpe": "Crêpe with toasted nuts and honey",
  "Banana Roll": "Banana roll with chocolate",
  "Strawberry Crêpe with Ice Cream": "Fresh strawberry crêpe with ice cream",
  "Mini Crêpe": "Mini creamy crêpe pieces with assorted sauces",
  // Waffles
  "Noor Land Waffle": "Chef's special waffle with chocolate and fruits",
  "Fruit Waffle": "Belgian waffle with fresh fruits",
  "Nuts Waffle": "Waffle with toasted nuts and honey",
  "Oreo Waffle": "Waffle with Oreo pieces and chocolate cream",
  "Lotus Waffle": "Waffle with lotus cream",
  "Nutella Waffle": "Waffle with Nutella cream",
  // Pancakes
  "Noor Land Pancake": "Chef's special pancake with fruits and chocolate",
  "Strawberry Pancake": "Pancake with fresh strawberry and sauce",
  "Banana Pancake": "Pancake with banana and honey",
  // Beverages
  "Soft Drinks": "Assorted chilled soft drinks",
  "Red Bull": "Chilled energy drink",
  "Sparkling Water": "Refreshing sparkling water",
  "Mineral Water 500ml": "500ml mineral water",
  "Mineral Water 1L": "1 liter mineral water",
  // Shisha
  "Double Apple Shisha": "Classic double apple flavor",
  "Citrus Shisha": "Refreshing citrus flavor",
  "Grape Shisha": "Sweet grape flavor",
  "Gum & Mint Shisha": "Gum flavor with a touch of mint",
  "Lemon Mint Shisha": "Lemon and mint flavor",
  "Orange Shisha": "Fresh orange flavor",
  "Double Apple Mint Shisha": "Double apple with a mint touch",
  "Mint Shisha": "Refreshing mint flavor",
  "Gum Shisha": "Classic gum flavor",
  "Bounty Shisha": "Bounty coconut and chocolate flavor",
  "Noor Land Shisha": "Noor Land special exclusive blend",
};

export function getDescEn(nameEn: string): string | null {
  return D[nameEn] ?? null;
}
